### ISSUE TITLE
Mood Board

### ISSUE THREAD

**Issue by LucasLassiter** [MJC-Computer-Science-Club/SantaPlatformer#1]
For now with the project, if you'd like to contribute, I think it'd be a good idea to put together a sort of "mood board" so we can nail down what we want to make.

There's two options I've found so far:

Option 1: https://goryana.itch.io/2d-and-3d-christmas-game-assets

Option 2: https://shubibubi.itch.io/winter-things

**Comment by zeapsu** [comment]
perms pls

**Comment by LucasLassiter** [comment]
Right away sir!

**Comment by LucasLassiter** [comment]
Just to update, it's been decided to use the 2D pixel art. Closing this issue.
